source 'https://github.com/CocoaPods/Specs.git'

# 忽略引入库的所有警告
inhibit_all_warnings!

platform :ios, '9.0'

target 'GKNavigationBarViewControllerDemo' do
  use_frameworks!

  pod 'Masonry'
  pod 'TZImagePickerController'
  pod 'IQKeyboardManager'

end
