source 'https://github.com/CocoaPods/Specs.git'

# 忽略引入库的所有警告
inhibit_all_warnings!

platform :ios, '9.0'

target 'GKNavigationBarViewControllerDemo' do
  use_frameworks!

  pod 'Masonry'
  pod 'TZImagePickerController'
  pod 'IQKeyboardManager'

end

#消除版本警告
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end

